name: Example - Basic SCA

on:
  push:
    branches: [ main ]
permissions:
  contents: read

jobs:
  sca-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Veracode Integration Hub (SCA)
        uses: JuanCunhaa/Veracode-Integration-Engine@main
        with:
          enableSCA: "true"
          scaToken: ${{ secrets.SRCCLR_API_TOKEN }}
